app = "dreamlayer-custom"
primary_region = "sjc"

[build]

[env]
  PORT = "5002"
  PYTHON_VERSION = "3.11"

[http_service]
  internal_port = 5002
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
