services:
  - type: web
    name: dreamlayer-backend
    env: python
    buildCommand: pip install -r dream_layer_backend/requirements_simple.txt
    startCommand: python3 dream_layer_backend/simple_api.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 5002
